name: mariable
description: Plateforme de réservation de prestataires de mariage inspirée d'Airbnb
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.6.0
  
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.5
 
  # État et Navigation
  flutter_bloc: ^9.1.0
  go_router: ^14.8.1

  # Sélection de fichiers et URLs
  image_picker: ^1.1.2
  path: ^1.8.3 
  url_launcher: ^6.1.11

  # Base de données et API
  supabase_flutter: ^2.8.4
  dio: ^5.3.2
 
  # Interface utilisateur
  flutter_hooks: ^0.21.2
  google_fonts: ^6.2.1
  cached_network_image: ^3.2.3
  flutter_svg: ^2.0.7

  fl_chart: ^0.70.2  # Pour les graphiques

  # Vidéo
  video_player: ^2.7.2
 
  # Formulaires et validation
  form_builder_validators: ^11.1.2
  flutter_form_builder: ^10.0.1

  # Authentication
 
  # Localisation et internationalisation
  intl: ^0.19.0
 
  # Utilitaires
  equatable: ^2.0.5
  uuid: ^4.5.1
  path_provider: ^2.1.1
  shared_preferences: ^2.2.1
  logger: ^2.5.0

  http: ^1.1.0
  webview_flutter_android: ^3.12.0
  webview_flutter: ^4.2.0
  flutter_plugin_android_lifecycle: ^2.0.15
  image_picker_android: ^0.8.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  bloc_test: ^10.0.0
  mockito: ^5.4.2
  build_runner: ^2.4.6

# Une seule section flutter ici
flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/videos/
    
   
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: assets/fonts/CustomFont-Regular.ttf
  #       - asset: assets/fonts/CustomFont-Bold.ttf
  #         weight: 700